<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-17T23:03:44 CST" name="Default suite" finished-at="2021-02-17T23:04:05 CST" duration-ms="21508">
    <groups>
    </groups>
    <test started-at="2021-02-17T23:03:44 CST" name="Default test" finished-at="2021-02-17T23:04:05 CST" duration-ms="21508">
      <class name="extentreport.GenerateExtentrepo">
        <test-method is-config="true" signature="setExtent()[pri:0, instance:extentreport.GenerateExtentrepo@120f102b]" started-at="2021-02-17T23:03:44 CST" name="setExtent" finished-at="2021-02-17T23:03:44 CST" duration-ms="525" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method is-config="true" signature="setup()[pri:0, instance:extentreport.GenerateExtentrepo@120f102b]" started-at="2021-02-17T23:03:44 CST" name="setup" finished-at="2021-02-17T23:03:54 CST" duration-ms="10050" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="freeCrmlogotest()[pri:0, instance:extentreport.GenerateExtentrepo@120f102b]" started-at="2021-02-17T23:03:54 CST" name="freeCrmlogotest" finished-at="2021-02-17T23:03:55 CST" duration-ms="176" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at extentreport.GenerateExtentrepo.freeCrmlogotest(GenerateExtentrepo.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- freeCrmlogotest -->
        <test-method is-config="true" signature="teardown(org.testng.ITestResult)[pri:0, instance:extentreport.GenerateExtentrepo@120f102b]" started-at="2021-02-17T23:03:55 CST" name="teardown" finished-at="2021-02-17T23:03:56 CST" duration-ms="1241" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=freeCrmlogotest status=FAILURE method=GenerateExtentrepo.freeCrmlogotest()[pri:0, instance:extentreport.GenerateExtentrepo@120f102b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:extentreport.GenerateExtentrepo@120f102b]" started-at="2021-02-17T23:03:56 CST" name="setup" finished-at="2021-02-17T23:04:03 CST" duration-ms="7310" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="freeCrmtitletest()[pri:0, instance:extentreport.GenerateExtentrepo@120f102b]" started-at="2021-02-17T23:04:03 CST" name="freeCrmtitletest" finished-at="2021-02-17T23:04:03 CST" duration-ms="21" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [#1 Free CRM customer relationship management software cloud111] but found [#1 Free CRM customer relationship management software cloud]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [#1 Free CRM customer relationship management software cloud111] but found [#1 Free CRM customer relationship management software cloud]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at extentreport.GenerateExtentrepo.freeCrmtitletest(GenerateExtentrepo.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- freeCrmtitletest -->
        <test-method is-config="true" signature="teardown(org.testng.ITestResult)[pri:0, instance:extentreport.GenerateExtentrepo@120f102b]" started-at="2021-02-17T23:04:03 CST" name="teardown" finished-at="2021-02-17T23:04:04 CST" duration-ms="1201" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=freeCrmtitletest status=FAILURE method=GenerateExtentrepo.freeCrmtitletest()[pri:0, instance:extentreport.GenerateExtentrepo@120f102b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:extentreport.GenerateExtentrepo@120f102b]" started-at="2021-02-17T23:04:04 CST" name="endReport" finished-at="2021-02-17T23:04:05 CST" duration-ms="914" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- extentreport.GenerateExtentrepo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
